import { Inter } from "next/font/google";
import "./globals.css";

/*--Components --*/
import Title from "@/components/Title";
import SearchBar from "@/components/SearchBar";
import MoviesList from "@/components/MoviesList";
import Movie from "@/components/Movie";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <Title>Search Movies</Title>
        <SearchBar />
        <MoviesList />
        <Movie />
      </body>
    </html>
  );
}
